# Generated by Django 4.1.3 on 2023-09-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cate',
                'verbose_name_plural': 'Cates',
            },
        ),
        migrations.CreateModel(
            name='Subj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subj_code', models.CharField(max_length=25)),
                ('subj_name', models.CharField(max_length=255)),
                ('credit', models.CharField(max_length=25)),
                ('semester', models.CharField(max_length=25)),
                ('year', models.CharField(max_length=25)),
                ('cate', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.cate')),
            ],
            options={
                'verbose_name': 'Subj',
                'verbose_name_plural': 'Subjs',
            },
        ),
    ]
